import type { Config } from "tailwindcss";

const config: Config = {
  content: [
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
    "./components/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        "on-primary-container": "#fffbff",
        "secondary-fixed": "#ffdcbd",
        "on-tertiary-container": "#fefee9",
        "secondary-container": "#ffca98",
        "on-primary": "#ffffff",
        "on-background": "#1b1c19",
        "inverse-surface": "#30312e",
        "on-tertiary": "#ffffff",
        "tertiary-container": "#757665",
        secondary: "#7d562d",
        error: "#ba1a1a",
        "tertiary-fixed": "#e4e4cf",
        "on-surface-variant": "#4e453f",
        "surface-tint": "#6c5b4d",
        "surface-dim": "#dbdad5",
        "surface-container-lowest": "#ffffff",
        "on-secondary-fixed-variant": "#623f18",
        "inverse-primary": "#d8c3b2",
        "on-secondary": "#ffffff",
        "on-error": "#ffffff",
        "on-tertiary-fixed": "#1b1d10",
        tertiary: "#5c5d4d",
        "on-surface": "#1b1c19",
        "surface-variant": "#e4e2dd",
        "on-error-container": "#93000a",
        "on-secondary-container": "#7a532a",
        "surface-container-low": "#f5f3ee",
        "error-container": "#ffdad6",
        "on-primary-fixed": "#25190f",
        "surface-container-highest": "#e4e2dd",
        "surface-bright": "#fbf9f4",
        background: "#fbf9f4",
        "on-primary-fixed-variant": "#534437",
        primary: "#69594b",
        "tertiary-fixed-dim": "#c8c8b4",
        "secondary-fixed-dim": "#f0bd8b",
        "inverse-on-surface": "#f2f1ec",
        "surface-container": "#f0eee9",
        "primary-fixed-dim": "#d8c3b2",
        "surface-container-high": "#eae8e3",
        outline: "#7f756e",
        surface: "#fbf9f4",
        "primary-fixed": "#f5decd",
        "primary-container": "#837163",
        "on-tertiary-fixed-variant": "#474839",
        "outline-variant": "#d1c4bb",
        "on-secondary-fixed": "#2c1600",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
      },
      spacing: {
        "container-padding-mobile": "20px",
        "stack-overlap": "-12px",
        "container-padding-desktop": "64px",
        gutter: "24px",
        unit: "8px",
      },
      fontFamily: {
        "label-caps": ["var(--font-source-serif)"],
        "annotation-sm": ["var(--font-bricolage)"],
        "body-md": ["var(--font-source-serif)"],
        "display-lg-mobile": ["var(--font-libre-caslon)"],
        "body-lg": ["var(--font-source-serif)"],
        "headline-md": ["var(--font-libre-caslon)"],
        "display-lg": ["var(--font-libre-caslon)"],
      },
      fontSize: {
        "label-caps": ["12px", { lineHeight: "16px", letterSpacing: "0.1em", fontWeight: "600" }],
        "annotation-sm": ["14px", { lineHeight: "20px", letterSpacing: "0.01em", fontWeight: "400" }],
        "body-md": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "display-lg-mobile": ["36px", { lineHeight: "44px", fontWeight: "400" }],
        "body-lg": ["18px", { lineHeight: "28px", fontWeight: "400" }],
        "headline-md": ["24px", { lineHeight: "32px", fontWeight: "400" }],
        "display-lg": ["48px", { lineHeight: "56px", letterSpacing: "-0.02em", fontWeight: "400" }],
      },
    },
  },
  plugins: [],
};

export default config;
